// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cbF4S8s5YG2dndlqE7wiUPtRUgsTmP0',
    appId: '1:765774350117:web:76202bb858d90f03f6fccc',
    messagingSenderId: '765774350117',
    projectId: 'rasa-d8546',
    authDomain: 'rasa-d8546.firebaseapp.com',
    storageBucket: 'rasa-d8546.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI8PxWRh-ptA8uZlFNNgaQgVVdSw6_x10',
    appId: '1:765774350117:android:ef5301212197d777f6fccc',
    messagingSenderId: '765774350117',
    projectId: 'rasa-d8546',
    storageBucket: 'rasa-d8546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOv_hRjZEIOaH_gqVjJX25IncgeaKktBU',
    appId: '1:765774350117:ios:2ab1a5ed930a2701f6fccc',
    messagingSenderId: '765774350117',
    projectId: 'rasa-d8546',
    storageBucket: 'rasa-d8546.firebasestorage.app',
    iosClientId: '765774350117-qoifjkrce20jcf1e1bo4bobhes8ebi3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectrasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOv_hRjZEIOaH_gqVjJX25IncgeaKktBU',
    appId: '1:765774350117:ios:2ab1a5ed930a2701f6fccc',
    messagingSenderId: '765774350117',
    projectId: 'rasa-d8546',
    storageBucket: 'rasa-d8546.firebasestorage.app',
    iosClientId: '765774350117-qoifjkrce20jcf1e1bo4bobhes8ebi3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectrasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3cbF4S8s5YG2dndlqE7wiUPtRUgsTmP0',
    appId: '1:765774350117:web:defed4b6ac695a0cf6fccc',
    messagingSenderId: '765774350117',
    projectId: 'rasa-d8546',
    authDomain: 'rasa-d8546.firebaseapp.com',
    storageBucket: 'rasa-d8546.firebasestorage.app',
  );
}
